### ISSUE TITLE
Failed resolving dependences while using Flutter under dev channel

### ISSUE THREAD

**Issue by unalone** [dart-lang/intl_translation#123]
It will report error like this:
==========================================
Running "flutter pub get" in app...                          
The current Dart SDK version is 2.12.0-141.0.dev.

Because intl_translation <0.17.0 requires SDK version >=1.12.0 <2.0.0 and intl_translation >=0.17.0 <0.17.7 depends on intl ^0.15.3, intl_translation <0.17.7 requires intl ^0.15.3.

And because intl_translation >=0.17.7 depends on intl >=0.15.3 <0.17.0 and every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2, intl_translation is incompatible with flutter_localizations from sdk.
So, because showme depends on both flutter_localizations any from sdk and intl_translation any, version solving failed.
pub get failed (1; So, because showme depends on both flutter_localizations any from sdk and intl_translation any, version solving failed.)
exit code 1

**Comment by rmgit** [comment]
also for current beta channel
Flutter 1.25.0-8.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8f89f6505b (vor 3 Wochen) • 2020-12-15 15:07:52 -0800
Engine • revision 92ae191c17
Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)


Because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2 and intl_translation 0.17.10+1 depends on intl >=0.15.3 <0.17.0, flutter_localizations from sdk is incompatible with intl_translation 0.17.10+1.
And because no versions of intl_translation match >0.17.10+1 <0.18.0, flutter_localizations from sdk is incompatible with intl_translation ^0.17.10+1.
So, because surec_app depends on both intl_translation ^0.17.10+1 and flutter_localizations any from sdk, version solving failed.
pub get failed (1; So, because surec_app depends on both intl_translation ^0.17.10+1 and flutter_localizations any from sdk, version solving failed.)
Process finished with exit code 1

**Comment by yanshouwang** [comment]
no solutions?

**Comment by rmgit** [comment]
> no solutions?
for me the following circumvention works 
```
  intl_translation:
    git:
      url: https://github.com/nt4f04uNd/intl_translation
```

**Comment by lifenautjoe** [comment]
> > no solutions?
> 
> for me the following circumvention works
> 
> ```
>   intl_translation:
>     git:
>       url: https://github.com/nt4f04uNd/intl_translation
> ```

I advise greatly not to add to your dependencies a package from an untrusted source.

We need an official solution.

**Comment by rmgit** [comment]
I gree that adding a package from an untrusted source to dependencies is not good.
Anyway it's possible to look at the code to get trust.

Beyond that.
With the great package update flood aroud sound null saftey I was able to upgrade the pub.dev package.
The circumvention is no longer needed/used by me.

I'm fine with closing the issue

> > > no solutions?
> > 
> > 
> > for me the following circumvention works
> > ```
> >   intl_translation:
> >     git:
> >       url: https://github.com/nt4f04uNd/intl_translation
> > ```
> 
> I advise greatly not to add to your dependencies a package from an untrusted source.
> 
> We need an official solution.

**Comment by Tejesh521** [comment]
>   intl_translation:
>     git:
>       url: https://github.com/nt4f04uNd/intl_translation

where should i add this ?? i mean in which file and which place i should place this !

**Comment by 726D** [comment]
@Tejesh521 this goes into the pubspec.yaml where intl_translation: normally is.
it just changes he source for the package from pubdev to the specified repo.

anyway i think thw workaround is no longer necessary if you have upgrades all packages to current and transitioned to sound null safety what i think is inevitable

**Comment by sgueko** [comment]
check these issue 

https://github.com/dart-lang/intl_translation/issues/142

**Comment by mosuem** [comment]
Closing in favor of #165 .
