### ISSUE TITLE
Is the package no longer supported?

### ISSUE THREAD

**Issue by tim-teacher** [dart-lang/intl_translation#167]
No any changes during last 2 years, no any support for latest version of Flutter. Is the package no longer supported? If yes, please add DEPRECATED to readme.md me to indicated that we should not use it any more.

**Comment by devoncarew** [comment]
We're in the process of updating this package to the latest package deps, lints, null safety, and re-publishing. Given that this package hasn't seen attention for a while, updating it will take a bit of time.

I'll ping this issue as we make progress, so interested parties can follow along.

**Comment by jbrownsw** [comment]
Note that in the meantime there is a fork https://github.com/kiwi-bop/intl_generator with null safety support you can use. I'm not associated with either project and have no real preference here. I'm just adding support for translations to our current project and the lack of null safety was a deal breaker for me so I had to use the fork instead.

**Comment by jodinathan** [comment]
@devoncarew do you have any updates on this please?

**Comment by mosuem** [comment]
@jodinathan I am currently starting to look into this repository, so you will probably see some progress soon :)

**Comment by iyuhang** [comment]
How are things going
@devoncarew 

$ flutter pub add intl_translation
The current Dart SDK version is 2.18.2.

Because intl_translation <0.17.0 requires SDK version >=1.12.0 <2.0.0 and intl_translation >=0.17.0 <0.17.7 depends on intl ^0.15.3, intl_translation <0.17.7 requires intl ^0.15.3.
And because intl_translation >=0.17.7 depends on intl >=0.15.3 <0.17.0, every version of intl_translation requires intl >=0.15.3 <0.17.0.
So, because renaapp depends on both intl ^0.17.0 and intl_translation any, version solving failed.

**Comment by mosuem** [comment]
The null-safety migration is currently in review and will land soon.

**Comment by mosuem** [comment]
The null safety migration has landed; closing this now.
