### ISSUE TITLE
how to use with the google Translate Toolkit ?

### ISSUE THREAD

**Issue by gedw99** [dart-lang/intl_translation#44]
so i upload a single international .arb to the Toolkit and need to magically get  many .arb out.

1. How to automate the upload to the toolkit ?
2. How to get many .arb out. I cant see how the Toolkit does that.

**Comment by freezy** [comment]
Also, even more important:

1. How to update a source `.arb` file as the consumer app get messages added, updated or removed
2. How to import an existing translated `.arb` file to be updated with a newer source

**Comment by alan-knight** [comment]
I am not an expert in Google Translator Toolkit, and note that it's not necessary to use that. It's just a free service which supports ARB files, which is our default output.

For the basic workflow, I found some instructions in an e-book [here](https://books.google.com/books?id=IHg5DwAAQBAJ&pg=PA412&lpg=PA412&dq=translation+ARB+file&source=bl&ots=ZC74_J2U6e&sig=UIwM5lHtXf27nEJmEoOkap-acac&hl=en&sa=X&ved=2ahUKEwjNh5yd7NneAhXIwFQKHb-RCgI4ChDoATACegQICBAB#v=onepage&q=translation%20ARB%20file&f=false). 

I don't know how to automate the upload. There was an API, but I haven't used it and it appears that it's no longer publicly available. Since it's a web API presumably you could script it a series of HTTP operations, but I have not tried that.

In general, when you upload a modified file, the entries which have previously been seen will automatically be populated with the updated translations. I'm not sure if the toolkit even distinguishes between uploading a new file and uploading an updated version. I believe it goes by the individual message content and knows which ones it already has translations for.

**Comment by freezy** [comment]
Well, re-uploading the same file to Translator Kit results in a second file appearing in the list with 0% translated, even though the original was translated. I can open it, and it will "intelligently" fill out values it can determine from my previous translations ("TM match"), but I suppose that's based on the actual content, not the key. I find it kind of obvious that Translator Kit is made for a hobbyist's one-time use and not for a professional continuous workflow.

So when you guys decided to go for ARB (and not, let's say, `.po`), what kind of workflow did you have in mind? I mean, Flutter is taking off and people need to translate their apps, right?

**Comment by alan-knight** [comment]
I agree it's likely based on the content. I don't know to what extent it shares with Google's internal translation infrastructure, but that is definitely content based. I can't comment on the intent of Translator Toolkit. If you have a professional tool that you prefer that's fine. We went with ARB (long before Flutter existed) because it was an easy format and it fully supported ICU semantics for translations (placeholders, plurals, genders). But it's as much an example as an endorsement. There are lots of formats and lots of tools. The format is entirely pluggable, and we use a different one internally. If you look at the extract and generate programs they are very small and mostly amount to writing a grammar for the format and a generator for it. It would be pretty straightforward to write that for another format if it supports the semantics. Or find (or write) a utility that converts between the file formats - they're not complicated. Even if the other format doesn't fully support the semantics (.po doesn't), you just have to decide what to do with things that the format doesn't support. But there is a [bug](https://github.com/dart-lang/intl/issues/137) to support loading the native translation formats for Android/iOS in order to re-use existing translations.

It's not even necessary to use the code generation approach that generate_from_arb uses. The underlying mechanism just wants to look up in a data structure, and that could be loaded in some other way without going through that step at all.

**Comment by freezy** [comment]
Fair enough. For what it's worth, I've already started working on an extract/generate script for a JSON structure that is supported by poeditor.com. They don't have genders but plural, but that's sufficient for our use case.

Would you be accepting a PR for such a feature?

**Comment by alan-knight** [comment]
Definitely, thanks. (Sorry for the delay, was out for an extended US Thanksgiving)
