### ISSUE TITLE
is generating the arb files override old?

### ISSUE THREAD

**Issue by amreniouinnovent** [dart-lang/intl_translation#67]
I want to use this library but I have a small question:
I wonder if generating the arb files will override the old values or it could be the same values?
For example, I translate some values to Arabic then I generated the files is it will override the old values?

**Comment by alan-knight** [comment]
It will overwrite. But normally these would be separate ARB files anyway, particularly because you will have different languages. So the flow would be 
  program -> extract_to_arb -> foo.arb
run through translation to produce foo_ar.arb, foo_en.arb, foo_pt.arb, etc.

Typically there would be some automated process/translation program in between so that when you regenerate foo.arb it will notice new/changed messages and get them translated.

**Comment by amreniouinnovent** [comment]
@alan-knight  Thank you I got the idea
once the intl_messages is generated I can translate it and append to the exit arb then I extract from it
