### ISSUE TITLE
Generate From Arb Regardless of Explicit references in Dart code?

### ISSUE THREAD

**Issue by AlabasterAxe** [dart-lang/intl_translation#79]
Hi,

I've spent a while trying to get a Flutter/Dart internationalization workflow up and running but I'm running into some blockers.

I've been using https://github.com/flutter/website/tree/master/examples/internationalization/intl_example as my reference.

The major difference is I'm not generating our ARB files with intl_translation:extract_to_arb. I am generating our ARB files independently but I'd still like to use intl_translation:generate_from_arb to auto generate our localized versions.

The problem is that generate_from_arb seems to require explicit references to the messages in our ARBs in our dart code, otherwise it doesn't add the messages to the notInlinedMessages in the autogenerated code.

Is there any way to get the generate_from_arb tool to not require explicit references to generate the localized files?

Please let me know if there's a better place for me to report this kind of issue.

Thanks,

Matt

**Comment by alan-knight** [comment]
This is a good place to report.

That is the behavior. The idea is that people may already have large catalogs of messages available, and we don't want to include them if they're not actually going to be called from the program. So I guess you're generating them but calling the translations in some other way than through Intl.message?

It's a bit tricky - the assumption that we have an originalMessage is fairly deep in the code, e.g. https://github.com/dart-lang/intl_translation/blob/fd896cdc50a15e1e3dfb3318cfef5409e34f3b55/lib/generate_localized.dart#L82

and the idea that we get those from parsing the .dart files is built into generate_from_arb.dart.  It ought to be possible to tell it to get the original messages by parsing another ARB file. We actually do that in the adaptor to Google's internal translation format, because it's faster than re-parsing the sources. But it's not a trivial fix.

Without diving into it deeper my thought for a quick workaround is that you could generate a Dart file from the ARB which had nothing but a shell of the message calls, feed that into generate_from_arb.dart and then ignore it otherwise. But that's a fair amount of work for a hacky workaround. Or you could fork generate_from_arb and convince it to parse the same ARB file to find the "original" messages instead of parsing Dart files.

I think the correct fix is one of 
* Not require the original message at all, and have an option for that
* Allow it to treat the translations as their own originals

**Comment by AlabasterAxe** [comment]
Hi Alan, 

Thanks for the quick response and sorry for the delay in responding! At first I did what you suggested and forked generate_from_arb and coerced it to generate the messages Dart file for all of the messages in the arb files with some mixed success (by the end it was adding every message twice for some reason!). In the end the effort turned out to be moot because we're going to be handling these messages separately so we won't be going through the dart Localizations utilities since these messages are more dynamic in nature.

Thanks again for the detailed and fast response!

Thanks,

Matt
